CREATE TABLE investment_funds (
    id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    isin VARCHAR(12) NOT NULL,
    name NVARCHAR(200) NOT NULL,
    management_company NVARCHAR(200) NULL,
    category NVARCHAR(100) NULL,
    currency CHAR(3) NOT NULL,
    inception_date DATE NULL,
    nav_date DATE NULL,
    nav DECIMAL(18,6) NULL,
    assets_under_management DECIMAL(20,2) NULL,
    investors INT NULL,
    management_fee DECIMAL(8,4) NULL,
    deposit_fee DECIMAL(8,4) NULL,
    ter DECIMAL(8,4) NULL,
    risk_level INT NULL,
    return_ytd DECIMAL(10,4) NULL,
    return_1_year DECIMAL(10,4) NULL,
    return_3_years DECIMAL(10,4) NULL,
    return_5_years DECIMAL(10,4) NULL,
    active BIT NOT NULL CONSTRAINT DF_investment_funds_active DEFAULT 1,
    created_at DATETIMEOFFSET NOT NULL CONSTRAINT DF_investment_funds_created_at DEFAULT SYSDATETIMEOFFSET(),
    updated_at DATETIMEOFFSET NULL,
    CONSTRAINT UQ_investment_funds_isin UNIQUE (isin),
    CONSTRAINT CK_investment_funds_risk_level CHECK (risk_level IS NULL OR risk_level BETWEEN 1 AND 7)
);
